### ISSUE TITLE
BeagleBone Green SPI0_CS1 pin?

### ISSUE THREAD

**Issue by cenotaph** [SeeedDocument/Seeed-WiKi#15]
The PINMAP_SPI.png for the BeagleBone green documentation lists both P9.19 and P9.42 as SPI1_CS1. Presumably one of these is SPI0_CS1 actually, since that doesn't otherwise appear.

**Comment by jerryyip** [comment]
That is Pin Reuse. You could choose one of them to use. The same as SPI1_CS0.
