### ISSUE TITLE
Only works with Arduino Leonardo

### ISSUE THREAD

**Issue by gabrielstellini** [SeeedDocument/Seeed-WiKi#17]
No support for mega/arduino uno!

**Comment by loovee** [comment]
Hello, which product do you mean.
Thanks.

Loovee

**Comment by gabrielstellini** [comment]
https://github.com/SeeedDocument/Wifi_Shield_Fi250_V1.1

**Comment by gabrielstellini** [comment]
Why did you close the issue after 3 months of inactivity?
